import { defineConfig } from "vite-plus";

export default defineConfig({
  pack: {
    tsconfig: "tsconfig.build.json",
    entry: [
      "src/index.ts",
      "src/Auth.ts",
      "src/Drizzle.ts",
      "src/DrizzleD1.ts",
      "src/DrizzleLibsql.ts",
      "src/DrizzleMysql2.ts",
      "src/DrizzlePglite.ts",
      "src/DrizzlePostgres.ts",
      "src/DrizzleSqliteBun.ts",
      "src/DrizzleSqliteDo.ts",
      "src/DrizzleSqliteNode.ts",
      "src/DrizzleSqliteWasm.ts",
      "src/Cloudflare.ts",
      "src/Http.ts",
      "src/HttpServer.ts",
      "src/OperationHttp.ts",
      "src/OperationHttpClient.ts",
      "src/OperationHttpServer.ts",
      "src/Atom.ts",
      "src/Hooks.ts",
      "src/Identity.ts",
      "src/OAuth.ts",
      "src/Operations.ts",
      "src/Rpc.ts",
      "src/Schema.ts",
      "src/Testing.ts",
      "src/WebCrypto.ts",
      "src/Sessions.ts",
      "src/SessionContract.ts",
      "src/Proofs.ts",
      "src/Password.ts",
      "src/Email.ts",
      "src/OpenIdClient.ts",
      "src/OpenIdClientConnected.ts",
      "src/Passkey.ts",
      "src/PasskeyPassword.ts",
      "src/PasskeySimpleWebAuthn.ts",
      "src/PasskeyBrowser.ts",
      "src/GitHub.ts",
      "src/AuthSession.ts",
      "src/Errors.ts",
      "src/Workflows.ts",
      "src/PasswordHasher.ts",
      "src/EmailOtp.ts",
      "src/AuthStore.ts",
      "src/PasswordAuth.ts",
      "src/Policy.ts",
      "src/EmailOtpSender.ts",
      "src/AuthTokenCodec.ts",
      "src/IdentityResolver.ts",
      "src/PasswordCredentialStore.ts",
      "src/PhoneOtp.ts",
      "src/Totp.ts",
      "src/PasskeyContract.ts",
      "src/TotpContract.ts",
    ],
    dts: true,
    sourcemap: true,
  },
  test: { cache: false, silent: "passed-only", include: ["test/**/*.test.ts"] },
});
